name: Deploy static site to Pages

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      # Change these environment variable names to match the secrets
      FIREBASE_API_KEY: ${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }}
      FIREBASE_AUTH_DOMAIN: ${{ secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }}
      FIREBASE_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }}
      FIREBASE_STORAGE_BUCKET: ${{ secrets.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET }}
      FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID }}
      FIREBASE_APP_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_APP_ID }}
      FIREBASE_MEASUREMENT_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID }}
      KAKAO_APP_KEY: ${{ secrets.YOUR_KAKAO_APP_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Debug Environment
        run: |
          echo "Current directory: $(pwd)"
          echo "Files in directory:"
          ls -la
          echo "Checking secrets.template.js:"
          cat secrets.template.js
    
      - name: Debug Template
        run: |
          echo "Template content:"
          cat secrets.template.js
          echo ""
          echo "Checking for placeholders:"
          grep -o "FIREBASE_[A-Z_]*" secrets.template.js || echo "No matches found"
    
      - name: Inject Secrets
        run: |
          cat > secrets.js << 'EOF'
          window.FIREBASE_CONFIG = {
            apiKey: "$FIREBASE_API_KEY",
            authDomain: "$FIREBASE_AUTH_DOMAIN",
            projectId: "$FIREBASE_PROJECT_ID",
            storageBucket: "$FIREBASE_STORAGE_BUCKET",
            messagingSenderId: "$FIREBASE_MESSAGING_SENDER_ID",
            appId: "$FIREBASE_APP_ID",
            measurementId: "$FIREBASE_MEASUREMENT_ID"
          };
          window.KAKAO_APP_KEY = "$KAKAO_APP_KEY";
          EOF
          
          # Replace environment variables in the file
          envsubst < secrets.js > secrets.tmp
          mv secrets.tmp secrets.js
          
          # Verify without showing content
          echo "secrets.js created successfully"
        env:
          FIREBASE_API_KEY: ${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }}
          FIREBASE_AUTH_DOMAIN: ${{ secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }}
          FIREBASE_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }}
          FIREBASE_STORAGE_BUCKET: ${{ secrets.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET }}
          FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID }}
          FIREBASE_APP_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_APP_ID }}
          FIREBASE_MEASUREMENT_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID }}
          KAKAO_APP_KEY: ${{ secrets.YOUR_KAKAO_APP_KEY }}

      - name: Verify Files
        run: |
          echo "Final directory contents:"
          ls -la
          echo "Checking secrets.js format:"
          head -n 1 secrets.js

      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add secrets.js
          git commit -m "Update secrets.js with injected values"
          git push
