name: Deploy static site to Pages

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Debug Environment
        run: |
          echo "Current directory: $(pwd)"
          echo "Files in directory:"
          ls -la
          echo "Checking secrets.template.js:"
          cat secrets.template.js

      - name: Inject Secrets
        run: |
          echo "Creating secrets.js from template..."
          cp secrets.template.js secrets.js
          
          echo "Replacing secrets..."
          sed -i "s|FIREBASE_API_KEY|${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }}|g" secrets.js
          sed -i "s|FIREBASE_AUTH_DOMAIN|${{ secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }}|g" secrets.js
          sed -i "s|FIREBASE_PROJECT_ID|${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }}|g" secrets.js
          sed -i "s|FIREBASE_STORAGE_BUCKET|${{ secrets.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET }}|g" secrets.js
          sed -i "s|FIREBASE_MESSAGING_SENDER_ID|${{ secrets.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID }}|g" secrets.js
          sed -i "s|FIREBASE_APP_ID|${{ secrets.NEXT_PUBLIC_FIREBASE_APP_ID }}|g" secrets.js
          sed -i "s|FIREBASE_MEASUREMENT_ID|${{ secrets.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID }}|g" secrets.js
          sed -i "s|KAKAO_APP_KEY|${{ secrets.YOUR_KAKAO_APP_KEY }}|g" secrets.js
          
          echo "Verifying secrets.js:"
          ls -la secrets.js
          echo "Contents of secrets.js:"
          cat secrets.js
          
          echo "Checking if secrets were replaced:"
          if grep -q "FIREBASE_" secrets.js; then
            echo "ERROR: Some secrets were not replaced!"
            exit 1
          else
            echo "All secrets were replaced successfully!"
          fi

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
