name: Deploy static site to Pages

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      # Using the exact repository secret names
      FIREBASE_API_KEY: ${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }}
      FIREBASE_AUTH_DOMAIN: ${{ secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }}
      FIREBASE_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }}
      FIREBASE_STORAGE_BUCKET: ${{ secrets.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET }}
      FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID }}
      FIREBASE_APP_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_APP_ID }}
      FIREBASE_MEASUREMENT_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID }}
      KAKAO_APP_KEY: ${{ secrets.YOUR_KAKAO_APP_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Create secrets.js
        run: |
          # Create a temporary directory for build artifacts
          mkdir -p .temp
          
          # Create the secrets.js file in the temporary directory
          cat > .temp/secrets.js << 'EOF'
          window.FIREBASE_CONFIG = {
            apiKey: "$FIREBASE_API_KEY",
            authDomain: "$FIREBASE_AUTH_DOMAIN",
            projectId: "$FIREBASE_PROJECT_ID",
            storageBucket: "$FIREBASE_STORAGE_BUCKET",
            messagingSenderId: "$FIREBASE_MESSAGING_SENDER_ID",
            appId: "$FIREBASE_APP_ID",
            measurementId: "$FIREBASE_MEASUREMENT_ID"
          };
          window.KAKAO_APP_KEY = "$KAKAO_APP_KEY";
          EOF
          
          # Replace environment variables in the file
          envsubst < .temp/secrets.js > .temp/secrets.tmp
          mv .temp/secrets.tmp .temp/secrets.js
          
          # Move the secrets.js to the public directory only for the build
          cp .temp/secrets.js public/secrets.js
          
          # Clean up temporary directory
          rm -rf .temp
          
          # Verify the file was created without showing its content
          echo "secrets.js created in public directory for build only"
        env:
          FIREBASE_API_KEY: ${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }}
          FIREBASE_AUTH_DOMAIN: ${{ secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }}
          FIREBASE_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }}
          FIREBASE_STORAGE_BUCKET: ${{ secrets.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET }}
          FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID }}
          FIREBASE_APP_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_APP_ID }}
          FIREBASE_MEASUREMENT_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID }}
          KAKAO_APP_KEY: ${{ secrets.YOUR_KAKAO_APP_KEY }}

      - name: Clean up secrets before deployment
        run: |
          # Remove the secrets.js file before deployment
          rm -f public/secrets.js
          echo "secrets.js removed before deployment"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages
          allow_empty_commit: false
          keep_files: false
          force_orphan: false
          enable_jekyll: false
          disable_nojekyll: false
          exclude_assets: .github
