name: Deploy static site to Pages

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      FIREBASE_API_KEY: ${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }}
      FIREBASE_AUTH_DOMAIN: ${{ secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }}
      FIREBASE_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }}
      FIREBASE_STORAGE_BUCKET: ${{ secrets.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET }}
      FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID }}
      FIREBASE_APP_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_APP_ID }}
      FIREBASE_MEASUREMENT_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID }}
      KAKAO_APP_KEY: ${{ secrets.YOUR_KAKAO_APP_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Debug Environment
        run: |
          echo "Current directory: $(pwd)"
          echo "Files in directory:"
          ls -la
          echo "Checking secrets.template.js:"
          cat secrets.template.js

      - name: Inject Secrets
        run: |
          echo "Removing existing secrets.js if it exists..."
          rm -f secrets.js
          
          echo "Creating secrets.js from template..."
          cp secrets.template.js secrets.js
          
          echo "Replacing secrets..."
          # Replace each secret individually and verify
          echo "Replacing FIREBASE_API_KEY..."
          sed -i "s|FIREBASE_API_KEY|${FIREBASE_API_KEY}|g" secrets.js
          echo "Replacing FIREBASE_AUTH_DOMAIN..."
          sed -i "s|FIREBASE_AUTH_DOMAIN|${FIREBASE_AUTH_DOMAIN}|g" secrets.js
          echo "Replacing FIREBASE_PROJECT_ID..."
          sed -i "s|FIREBASE_PROJECT_ID|${FIREBASE_PROJECT_ID}|g" secrets.js
          echo "Replacing FIREBASE_STORAGE_BUCKET..."
          sed -i "s|FIREBASE_STORAGE_BUCKET|${FIREBASE_STORAGE_BUCKET}|g" secrets.js
          echo "Replacing FIREBASE_MESSAGING_SENDER_ID..."
          sed -i "s|FIREBASE_MESSAGING_SENDER_ID|${FIREBASE_MESSAGING_SENDER_ID}|g" secrets.js
          echo "Replacing FIREBASE_APP_ID..."
          sed -i "s|FIREBASE_APP_ID|${FIREBASE_APP_ID}|g" secrets.js
          echo "Replacing FIREBASE_MEASUREMENT_ID..."
          sed -i "s|FIREBASE_MEASUREMENT_ID|${FIREBASE_MEASUREMENT_ID}|g" secrets.js
          echo "Replacing KAKAO_APP_KEY..."
          sed -i "s|KAKAO_APP_KEY|${KAKAO_APP_KEY}|g" secrets.js
          
          echo "Verifying secrets.js:"
          ls -la secrets.js
          echo "Checking if template placeholders remain:"
          if grep -q "FIREBASE_" secrets.js || grep -q "KAKAO_APP_KEY" secrets.js; then
            echo "ERROR: Some placeholders were not replaced!"
            echo "Current content of secrets.js:"
            cat secrets.js
            exit 1
          else
            echo "All placeholders were replaced successfully!"
            echo "Final content of secrets.js:"
            cat secrets.js
          fi

      - name: Verify Files
        run: |
          echo "Final directory contents:"
          ls -la
          echo "Checking secrets.js format:"
          head -n 1 secrets.js

      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add secrets.js
          git commit -m "Update secrets.js with injected values"
          git push
