name: Deploy static site to Pages

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Inject Secrets
        run: |
          cp secrets.template.js secrets.js
          sed -i "s|FIREBASE_API_KEY|${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }}|g" secrets.js
          sed -i "s|FIREBASE_AUTH_DOMAIN|${{ secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }}|g" secrets.js
          sed -i "s|FIREBASE_PROJECT_ID|${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }}|g" secrets.js
          sed -i "s|FIREBASE_STORAGE_BUCKET|${{ secrets.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET }}|g" secrets.js
          sed -i "s|FIREBASE_MESSAGING_SENDER_ID|${{ secrets.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID }}|g" secrets.js
          sed -i "s|FIREBASE_APP_ID|${{ secrets.NEXT_PUBLIC_FIREBASE_APP_ID }}|g" secrets.js
          sed -i "s|FIREBASE_MEASUREMENT_ID|${{ secrets.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID }}|g" secrets.js
          sed -i "s|KAKAO_APP_KEY|${{ secrets.YOUR_KAKAO_APP_KEY }}|g" secrets.js
          # Verify the file was created and contains the secrets
          echo "Verifying secrets.js:"
          cat secrets.js
          echo "Checking if secrets were replaced:"
          grep -v "FIREBASE_" secrets.js || echo "Secrets not properly replaced!"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages
          commit_message: "Deploy: ${{ github.event.head_commit.message }}"
